# This workflow uses Flyway Hub to test the migrations in the 'sql' directory.
#
# In order to use this workflow you will need to create a Github Actions secret called
# FLYWAY_HUB_ACCESS_TOKEN containing a valid Flyway Hub API access token.
#
name: Test Migrations on Flyway Hub

on:
  schedule:
   - cron: '0 5 * * 1-5'
  workflow_dispatch: {}

jobs:
  test-migrations:
    name: Test flyway migration scripts
    runs-on: ubuntu-latest
    steps:
      - name: Test migrations on Flyway Hub
        uses: andrew-farries/flyway-hub-migration-test@main
        with:
          projectId: 5
env:
  FLYWAY_HUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}
